[package]
name = "logshipper"
description = "Ships logs to lognplot GUI."
version = "0.1.0"
authors = ["Windel Bouwman <windel@windel.nl>"]
edition = "2018"

[dependencies]
lognplot = { path = "../lognplot" }
regex = "1"
